### ISSUE TITLE
How is any different then connect-query?

### ISSUE THREAD

**Issue by scottcorgan** [springernature/qs-middleware#1]
`connect-query` has been around awhile and downloaded quite a bit (https://www.npmjs.com/package/connect-query). Curious why another module had to be built.

**Comment by josebolos** [comment]
Hi @scottcorgan 

Sorry we missed this Issue! It looks like the module that you linked hasn't been updated in years. It also seem to be using an ancient version of `qs` (1.1.0) which has a number of vulnerabilities, according to nsp and snyk.

I hope that helps.
